from types import MappingProxyType

ALL_PERSON_FIELDS = MappingProxyType({
    'ADDRESSES': 'addresses',
    'AGE_RANGES': 'ageRanges',
    'BIOGRAPHIES': 'biographies',
    'BIRTHDAYS': 'birthdays',
    'COVER_PHOTOS': 'coverPhotos',
    'EMAIL_ADDRESSES': 'emailAddresses',
    'EVENTS': 'events',
    'GENDERS': 'genders',
    'IM_CLIENTS': 'imClients',
    'INTERESTS': 'interests',
    'LOCALES': 'locales',
    'MEMBERSHIPS': 'memberships',
    'METADATA': 'metadata',
    'NAMES': 'names',
    'NICK_NAMES': 'nicknames',
    'OCCUPATIONS': 'occupations',
    'ORGANIZATIONS': 'organizations',
    'PHONE_NUMBERS': 'phoneNumbers',
    'PHOTOS': 'photos',
    'RELATIONS': 'relations',
    'RESIDENCES': 'residences',
    'SIP_ADDRESSES': 'sipAddresses',
    'SKILLS': 'skills',
    'URLS': 'urls',
    'USER_DEFINED': 'userDefined',
})
